$(document).ready(function(){

    $("#body_poluicao").click(function(){
        let sound_underwater = document.getElementById('beep_underwater')
        sound_underwater.volume = 0.3
        sound_underwater.play();
    });


    $("#but1").click(function(){
        $('#pop1').show();
        $('#pop8').hide();
        $('#pop2').hide();
        $('#pop3').hide();
        $('#pop4').hide();
        $('#pop5').hide();
        $('#pop6').hide();
        $('#pop7').hide();
        $('#pop9').hide();
        $('#pop10').hide();
    }); 
    $("#but2").click(function(){
        $('#pop2').show();
        $('#pop1').hide();
        $('#pop8').hide();
        $('#pop3').hide();
        $('#pop4').hide();
        $('#pop5').hide();
        $('#pop6').hide();
        $('#pop7').hide();
        $('#pop9').hide();
        $('#pop10').hide();
    }); 
    $("#but3").click(function(){
        $('#pop3').show();
        $('#pop1').hide();
        $('#pop2').hide();
        $('#pop8').hide();
        $('#pop4').hide();
        $('#pop5').hide();
        $('#pop6').hide();
        $('#pop7').hide();
        $('#pop9').hide();
        $('#pop10').hide();
    }); 
    $("#but4").click(function(){
        $('#pop4').show();
        $('#pop1').hide();
        $('#pop2').hide();
        $('#pop3').hide();
        $('#pop8').hide();
        $('#pop5').hide();
        $('#pop6').hide();
        $('#pop7').hide();
        $('#pop9').hide();
        $('#pop10').hide();
    }); 
    $("#but5").click(function(){
        $('#pop5').show();
        $('#pop1').hide();
        $('#pop2').hide();
        $('#pop3').hide();
        $('#pop4').hide();
        $('#pop8').hide();
        $('#pop6').hide();
        $('#pop7').hide();
        $('#pop9').hide();
        $('#pop10').hide();
    }); 
    $("#but6").click(function(){
        $('#pop6').show();
        $('#pop1').hide();
        $('#pop2').hide();
        $('#pop3').hide();
        $('#pop4').hide();
        $('#pop5').hide();
        $('#pop8').hide();
        $('#pop7').hide();
        $('#pop9').hide();
        $('#pop10').hide();
    }); 
    $("#but7").click(function(){
        $('#pop7').show();
        $('#pop1').hide();
        $('#pop2').hide();
        $('#pop3').hide();
        $('#pop4').hide();
        $('#pop5').hide();
        $('#pop6').hide();
        $('#pop8').hide();
        $('#pop9').hide();
        $('#pop10').hide();
    }); 
    $("#but8").click(function(){
        $('#pop8').show();
        $('#pop1').hide();
        $('#pop2').hide();
        $('#pop3').hide();
        $('#pop4').hide();
        $('#pop5').hide();
        $('#pop6').hide();
        $('#pop7').hide();
        $('#pop9').hide();
        $('#pop10').hide();
    }); 
    $("#but9").click(function(){
        $('#pop9').show();
        $('#pop1').hide();
        $('#pop2').hide();
        $('#pop3').hide();
        $('#pop4').hide();
        $('#pop5').hide();
        $('#pop6').hide();
        $('#pop7').hide();
        $('#pop8').hide();
        $('#pop10').hide();
    }); 
    $("#but10").click(function(){
        $('#pop10').show();
        $('#pop1').hide();
        $('#pop2').hide();
        $('#pop3').hide();
        $('#pop4').hide();
        $('#pop5').hide();
        $('#pop6').hide();
        $('#pop7').hide();
        $('#pop8').hide();
        $('#pop9').hide();
    }); 
});